WebsiteQuyetTien_byAurora Team/Controllers/ProductTypeController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using WebsiteQuyetTien_byAurora_Team.Models;

namespace WebsiteQuyetTien_byAurora_Team.Controllers
{
    public class ProductTypeController : Controller
    {
        private DmQT08Entities db = new DmQT08Entities();

        // GET: ProductType
        public ActionResult Index()
        {
            if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")
            {
                return RedirectToAction("Index", "Home");
            }
            ViewBag.TenTaiKhoan = Session["TaiKhoan"];
            //var product = db.Products.OrderBy(x => x.ID).ToList();
            return View();
        }

        public ActionResult getTypeProduct()
        {
            db.Configuration.ProxyCreationEnabled = false;
            var productType = db.ProductTypes.Select(p => new
            {
                p.ID,
                p.ProductTypeCode,
                p.ProductTypeName,
            }).OrderByDescending(x=>x.ID).ToList();
            return Json(productType, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult getTypeID(int id)
        {
            db.Configuration.ProxyCreationEnabled = false;
            var productType = db.ProductTypes.Where(x => x.ID == id).Select(p => new
            {
                p.ProductTypeCode,
                p.ProductTypeName,
            }).FirstOrDefault();
            return Json(productType, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult SaveEntity(ProductType productType)
        {
            db.Configuration.ProxyCreationEnabled = false;
            if (!ModelState.IsValid)
            {
                IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                if (productType.ID == 0)
                {
                    db.ProductTypes.Add(productType);
                }
                else
                {
                    db.Entry(productType).State = EntityState.Modified;
                }
                db.SaveChanges();
                return Json(productType, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult DangXuat()
        {
            Session["TaiKhoan"] = null;
            return RedirectToAction("Index", "Login", new { area = "" });
        }
    }
}

WebsiteQuyetTien_byAurora Team/Views/Shared/DoanhMuc1Partial.cshtml
<div class="col-lg-3">
    <!-- *** KHU VỰC MENU *** -->
    <div class="card sidebar-menu mb-4">
        <div class="card-header">
            <h3 class="h4 card-title">Danh mục</h3>
        </div>
        <div class="card-body">
            <ul class="nav nav-pills flex-column">
                <li>
                    <a href="@Url.Action("About","Home")" class="nav-link">
                        <i class="fa fa-arrow-right"
                           aria-hidden="true"></i>Về Quyết Tiến
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("News","Home")" class="nav-link">
                        <i class="fa fa-arrow-right"
                           aria-hidden="true"></i>Tin Tức Và Sự Kiện
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Contactus","Home")" class="nav-link">
                        <i class="fa fa-arrow-right"
                           aria-hidden="true"></i>Liên Hệ
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("InstallmentHelper","Home")" class="nav-link">
                        <i class="fa fa-arrow-right"
                           aria-hidden="true"></i>Hướng dẫn mua
                        trả góp
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <!-- *** HẾT KHU VỰC MENU  ***-->
    <div class="banner">
        <a href="#"><img src="~/www.root/shared/user_layout/img/banner.jpg" alt="sales 2014" class="img-fluid"></a>
    </div>
</div>                

WebsiteQuyetTien_byAurora Team/Views/Shared/FooterUserLayoutPatial.cshtml
<!-- --------------------------------------------- -->
<!-- *** FOOTER *** -->
<div id="footer">
    <div class="container">
        <div class="row">
            <!-- *** VỀ QUYẾT TIẾN *** -->
            <div class="col-lg-3 col-md-6">
                <h4 class="mb-3">VỀ QUYẾT TIẾN</h4>
                <ul class="list-unstyled">
                    <li><a href="@Url.Action("About","Home")">Giới thiệu Quyết Tiến</a></li>
                    <li><a href="@Url.Action("Index","Login")">Tới trang Admin</a></li>
                </ul>
            </div>
            <!-- *** HẾT VỀ QUYẾT TIẾN *** -->
            <!-- --------------------------------------------- -->
            <!-- *** HỖ TRỢ KHÁCH HÀNG *** -->
            <div class="col-lg-3 col-md-6">
                <h4 class="mb-3">HỖ TRỢ KHÁCH HÀNG</h4>
                <ul class="list-unstyled">
                    <li><span class="text-danger font-weight-bold">Hotline: 1900 1829</span></li>
                    <li><a href="@Url.Action("Contactus","Home")">Gửi yêu cầu hỗ trợ</a></li>
                    <li><a href="@Url.Action("InstallmentHelper","Home")">Hướng dẫn mua trả góp</a></li>
                </ul>
            </div>
            <!-- *** HẾT HỖ TRỢ KHÁCH HÀNG *** -->
            <!-- --------------------------------------------- -->
            <!-- *** PHƯƠNG THỨC THANH TOÁN *** -->
            <div class="col-lg-3 col-md-6 mb-2">
                <h4 class="mb-3">PHƯƠNG THỨC THANH TOÁN</h4>
                <i class="paymenticon icon-cash"></i>
                <i class="paymenticon icon-installment"></i>
                <i class="paymenticon icon-visa"></i>
                <i class="paymenticon icon-mastercard"></i>
            </div>
            <!-- *** HẾT PHƯƠNG THỨC THANH TOÁNH *** -->
            <!-- --------------------------------------------- -->
            <!-- *** KẾT NỐI VỚI CHÚNG TÔI *** -->
            <div class="col-lg-3 col-md-6">
                <h4 class="mb-3">KẾT NỐI VỚI CHÚNG TÔI</h4>
                <p class="social">
                    <a href="#" class="facebook external"><i class="fa fa-facebook"></i></a>
                    <a href="#" class="email external"><i class="fa fa-envelope"></i></a>
                </p>
                <hr>
                <!-- --------------------------------------------- -->
                <h4 class="mb-3">ĐĂNG KÝ NHẬN BẢN TIN</h4>
                <p class="text-muted">Đừng bỏ lỡ hàng ngàn sản phẩm và chương trình khuyến mãi siêu hấp dẫn.</p>
                <form>
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Địa chỉ email của bạn"><span class="input-group-append">
                            <button type="button" class="btn btn-primary">Đăng ký</button>
                        </span>
                    </div>
                </form>
            </div>
            <!-- *** HẾT KẾT NỐI VỚI CHÚNG TÔI *** -->
        </div>
    </div>
</div>
<!-- *** HẾT FOOTER *** -->
<!-- --------------------------------------------- -->
<!-- *** BẢN QUYỀN *** -->
<div id="copyright">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 mb-2 mb-lg-0">
                <p class="text-center text-lg-left">© 2018 - Bản quyền của Công ty Quyết Tiến - quyettien.com</p>
                <p class="text-center text-lg-left">
                    Giấy chứng nhận Đăng ký Kinh doanh số 0123456789 do Sở Kế hoạch và
                    Đầu tư Thành phố Hồ Chí Minh cấp ngày 01/01/2018
                </p>
            </div>
        </div>
    </div>
</div>
<!-- *** HẾT BẢN QUYỀN *** -->
<!-- --------------------------------------------- -->

WebsiteQuyetTien_byAurora Team/Views/Shared/HeaderUserLayoutPartial.cshtml
<!-- *** HEADER ***  -->
<header class="header mb-5 sticky-top">
    <!-- *** NAVBAR *** --->
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a href="@Url.Action("Index","Home")" class="navbar-brand home">
                <img src="@Url.Content("~/www.root/shared/user_layout/img/logo.png")" alt="Logo Quyết Tiến" class="d-none d-md-inline-block" style="height: 70px">
                <img src="@Url.Content("~/www.root/shared/user_layout/img/logo.png")" alt="Logo Quyết Tiến" class="d-inline-block d-md-none" style="height: 70px">
                <span class="sr-only">Quyết Tiến - Trang chủ</span>
            </a>
            <div class="navbar-buttons">
                <button type="button" data-toggle="collapse" data-target="#navigation"
                        class="btn btn-outline-secondary navbar-toggler">
                    <span class="sr-only">Chuyển đổi điều hướng</span><i class="fa fa-align-justify"></i>
                </button>
                <button type="button" data-toggle="collapse" data-target="#search"
                        class="btn btn-outline-secondary navbar-toggler">
                    <span class="sr-only">Chuyển đổi tìm kiếm</span><i class="fa fa-search"></i>
                </button>
            </div>
            <div id="navigation" class="collapse navbar-collapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item"><a href="@Url.Action("Index","Home")" class="nav-link active text-white">Trang chủ</a></li>
                    <li class="nav-item dropdown menu-large">
                        <a href="#" data-toggle="dropdown" data-hover="dropdown"
                           data-delay="200" class="dropdown-toggle nav-link">
                            Sản
                            phẩm<b class="caret"></b>
                        </a>
                        @Html.Action("MenuPartial","Home")
                        
                    </li>
                    <li class="nav-item"><a href="@Url.Action("News","Home")" class="nav-link">Tin tức</a></li>
                    <li class="nav-item"><a href="@Url.Action("About","Home")" class="nav-link">Về chúng tôi</a></li>
                    <li class="nav-item"><a href="@Url.Action("Contactus","Home")" class="nav-link">Liên hệ</a></li>
                    <li class="nav-item"><a href="@Url.Action("InstallmentHelper","Home")" class="nav-link">Mua trả góp</a></li>
                </ul>
                <div class="navbar-buttons d-flex justify-content-end">
                    @using (Html.BeginForm("Search","Home",FormMethod.Post,new { @class = "form-inline"}))
                    {
                        <input type="text" placeholder="Tìm kiếm" class="form-control" id="SearchInput" style="width:180px" name="searchKey">
                        <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
                    }

                </div>
            </div>
        </div>
    </nav>
    <!-- *** HẾT NAVBAR *** -->
    <!-- --------------------------------------------- -->
    <!-- *** CÔNG CỤ TÌM KIẾM *** -->
    @*@Html.Action("Search","Home")*@
    <!-- *** HẾT CÔNG CỤ TÌM KIẾM *** -->
</header>
<!-- *** HẾT HEADER *** -->
<!-- --------------------------------------------- -->

WebsiteQuyetTien_byAurora Team/Views/Shared/_AdminLayput.cshtml
@using WebsiteQuyetTien_byAurora_Team.Models;
@{Account account = (Account)Session["acc"];
}
<!DOCTYPE html>

<html>
<head>
    <title>Quản lý Điện máy Quyết Tiến</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Gretong Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,

        Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <link rel="shortcut icon" href="~/www.root/controller/loginController/images/favicon.png" />
    <link href="~/www.root/controller/productController/Css/manageProduct.css" rel="stylesheet" />
    <!-- Bootstrap Core CSS -->
    @*<link href="~/www.root/shared/admin_layout/Admin/css/bootstrap.min.css" rel="stylesheet" />*@
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Custom CSS -->
    <link href="~/www.root/shared/admin_layout/Admin/css/style.css" rel='stylesheet' type='text/css' />
    <!-- Graph CSS -->
    <link href="~/www.root/shared/admin_layout/Admin/css/font-awesome.css" rel="stylesheet">
    <!-- jQuery -->
    <link href='//fonts.googleapis.com/css?family=Roboto:700,500,300,100italic,100,400' rel='stylesheet' type='text/css' />
    <link href='//fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link href="~/lib/notifyjs/dist/styles/metro/notify-metro.css" rel="stylesheet" />
    <!-- lined-icons -->
    <link rel="stylesheet" href="~/www.root/shared/admin_layout/Admin/css/icon-font.min.css" type='text/css' />
    <!-- //lined-icons -->
    <!-- //lined-icons -->
    @*<script src="~/www.root/shared/admin_layout/Admin/js/jquery-1.10.2.min.js"></script>*@
    <!-- jQuery -->
    <script src="~/lib/jquery/dist/jquery.js" charset="utf-8"></script>
    <script src="~/lib/jquery-ui/jquery-ui.js" type="text/javascript" charset="utf-8"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
  
    <!-- Datatable-->
    <!--Font Awesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    @RenderSection("Styles", false)
</head>
<body>
    <div id="overlayer"></div>
    <span class="loader">
        <span class="loader-inner"></span>
    </span>
    <div class="page-container">
        <!--/content-inner-->
        <div class="left-content">
            <div class="inner-content">
                <!-- header-starts -->
                <div class="header-section">
                    <!-- top_bg -->
                    <div class="top_bg">

                        <div class="header_top">
                            <div class="top_right">
                                <ul>
                                    <li><a href="@Url.Action("Index","Home")">Trang khách hàng</a></li>|
                                    <li><a href="@Url.Action("Contactus","Home")">Hổ trợ kỹ thuật</a></li>|
                                </ul>
                            </div>
                            <div class="top_left">

                                <h2>Chào:  @ViewBag.TenTaiKhoan @Html.ActionLink("Đăng xuất", "DangXuat", "Login", new { @class = "btn btn-primary" })
                            </div>
                            <div class="clearfix"> </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <!-- /top_bg -->
                </div>

                <!-- //header-ends -->
                <!--content-->
                <div class="content">
                    @RenderBody()

                    <!--Footer layout-->

                    <div class="footer">
                        <p>© 2018 Đồ án <Strong style="color: red;">Quyết Tiến</Strong> cho môn học | Thiết kế bởi <a href="http://w3layouts.com/">W3layouts</a> | Xây dựng bởi <Strong style="color: aquamarine">Aurora</Strong> và <strong style="color: darkblue">DevWeb</strong></p>
                    </div>

                    <!--End Footer Layout-->
                </div>
                <!--content-->
            </div>
        </div>
        <!--//content-inner-->
        <!--/sidebar-menu-->
        <div class="sidebar-menu">
            <header class="logo1">
                <a href="@Url.Action("Index","Manage")" class="logoQT"><img src="~/www.root/shared/admin_layout/Admin/images/logo.png" class="img-responsive" alt="" style="width: 125px; display: inline;"> </a>
                <a href="#" class="sidebar-icon"> <span class="fa fa-bars"></span> </a>
            </header>
            <div style="border-top:1px ridge rgba(255, 255, 255, 0.15)"></div>
            <div class="menu">
                <ul id="menu">
                    <li><a href="@Url.Action("Index","Manage")"><i class="fas fa-home"></i> <span>Trang Chủ</span></a></li>
                    <li id="menu-academico">
                        <a href="@Url.Action("Index","Manage")"><i class="fa fa-table"></i> <span> Sản phẩm</span> <span class="fa fa-angle-right" style="float: right"></span></a>
                        <ul id="menu-academico-sub">
                            <li id="menu-academico-avaliacoes"><a href="@Url.Action("Index","Manage")">Danh sách sản phẩm</a></li>
                            <li id="menu-academico-boletim"><a href="@Url.Action("Index","Manage")">Thêm sản phẩm</a></li>
                        </ul>
                    </li>
                    <li id="menu-academico">
                        <a href="#"><i class="fas fa-money-bill"></i> <span> Hóa đơn tiền mặt</span> <span class="fa fa-angle-right" style="float: right"></span></a>
                        <ul id="menu-academico-sub">
                            <li id="menu-academico-avaliacoes"><a href="@Url.Action("Index","ManageCashBill")">Danh sách hóa đơn tiền mặt</a></li>
                            <li id="menu-academico-boletim"><a href="@Url.Action("Index","ManageCashBill")">Thêm hóa đơn tiền mặt</a></li>
                            <li id="menu-academico-boletim"><a href="@Url.Action("Index","ManageCashBill")">In hóa đơn tiền mặt</a></li>
                        </ul>
                    </li>
                    <li id="menu-academico">
                        <a href="#"><i class="lnr lnr-book"></i> <span> Hóa đơn trả góp</span> <span class="fa fa-angle-right" style="float: right"></span></a>
                        <ul id="menu-academico-sub">
                            <li id="menu-academico-avaliacoes"><a href="@Url.Action("Index","ManageInstallmentBill")">Danh sách hóa đơn trả góp</a></li>
                            <li id="menu-academico-boletim"><a href="@Url.Action("Index","ManageInstallmentBill")">Thêm hóa đơn trả góp</a></li>
                            <li id="menu-academico-boletim"><a href="@Url.Action("Index","ManageInstallmentBill")">In hóa đơn trả góp</a></li>
                        </ul>
                    </li>
                    <li id="menu-academico">
                        <a href="#"><i class="fa fa-table"></i> <span> Quản lý doanh mục</span> <span class="fa fa-angle-right" style="float: right"></span></a>
                        <ul id="menu-academico-sub">
                            <li id="menu-academico-avaliacoes"><a href="@Url.Action("Index","ManageManufacture")">Quản lý nhà cung cấp</a></li>
                            <li id="menu-academico-boletim"><a href="@Url.Action("Index","ProductType")">Phân Loại sản phẩm</a></li>
                        </ul>
                    </li>
                    <li id="menu-academico">
                        <a href="#"><i class="lnr lnr-book"></i> <span> Quản lý khách hàng</span> <span class="fa fa-angle-right" style="float: right"></span></a>
                        <ul id="menu-academico-sub">
                            <li id="menu-academico-avaliacoes"><a href="@Url.Action("Index","ManageCustomer")">Danh sách khách hàng</a></li>
                            <li id="menu-academico-boletim"><a href="@Url.Action("Index","ManageCustomer")">Thêm thông tin</a></li>
                        </ul>
                    </li>
                    @*<li id="menu-academico"><a href="sunglasses.html"><i class="fas fa-gift"></i> <span>Quản lý khuyến Mãi</span></a></li>
                    <li><a href="sweater.html"><i class="fas fa-newspaper"></i> <span>Tin tức sự kiện</span></a></li>
                    <li id="menu-academico"><a href="catalog.html"><i class="fas fa-boxes"></i> <span>Phân Loại sản phẩm</span></a></li>
                    <li id="menu-academico"><a href="shoes.html"><i class="fas fa-chart-area"></i> <span>Thống kê doanh thu</span></a></li>*@
                    
                </ul>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <script>
        $(window).load(function () {
            $(".loader").delay(2000).fadeOut("slow");
            $("#overlayer").delay(2000).fadeOut("slow");
        })
    </script>
    <script>
        var toggle = true;

        $(".sidebar-icon").click(function () {
            if (toggle) {
                $(".page-container").addClass("sidebar-collapsed").removeClass("sidebar-collapsed-back");
                $("#menu span").css({ "position": "absolute" });
                $(".logoQT").css({ "display": "none" });
            }
            else {
                $(".page-container").removeClass("sidebar-collapsed").addClass("sidebar-collapsed-back");
                setTimeout(function () {
                    $("#menu span").css({ "position": "relative" });
                }, 400);
                $(".logoQT").css({ "display": "unset" });
            }

            toggle = !toggle;
        });
    </script>
    <!--js -->
    <script src="~/www.root/shared/admin_layout/Admin/js/jquery.nicescroll.js"></script>
    <script src="~/www.root/shared/admin_layout/Admin/js/scripts.js"></script>
    <!-- Bootstrap Core JavaScript -->
    @*<script src="~/www.root/shared/admin_layout/Admin/js/bootstrap.min.js"></script>*@
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/www.root/shared/admin_layout/Admin/js/menu_jquery.js"></script>
    <!-- jQuery -->
    <script src="~/lib/jquery/dist/jquery.js" charset="utf-8"></script>
    <script src="~/lib/jquery-ui/jquery-ui.js" type="text/javascript" charset="utf-8"></script>
    <!-- Bootstrap -->
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>*@
    <!-- FastClick -->
    <script src="~/lib/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="~/lib/nprogress/nprogress.js"></script>
    <!-- Chart.js -->
    <script src="~/lib/mustache/mustache.js"></script>
    <script src="~/lib/twbs-pagination/jquery.twbsPagination.js"></script>
    <script src="~/lib/chart.js/dist/Chart.js"></script>

    <script src="~/lib/ckeditor/ckeditor.js" charset="utf-8"></script>
    <!-- jQuery Sparklines -->
    <script src="~/lib/jquery-sparkline/dist/jquery.sparkline.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation/dist/additional-methods.js"></script>
    <script src="~/lib/jquery-validation/dist/Localization/messages_vi.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="~/lib/notifyjs/dist/notify.js"></script>
    <script src="~/lib/notifyjs/dist/styles/metro/notify-metro.js"></script>
    <script src="~/lib/bootbox/bootbox.js"></script>
    <!-- Bootstrap core JavaScript-->
    @*<script src="~/Scripts/jquery.min.js"></script>*@
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    @*<script src="~/Scripts/jquery.easing.min.js"></script>*@
    <!--Table-->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <!-- Custom Script-->
    <script src="~/www.root/shared/general.js"></script>
    <!--Select 2-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

    @RenderSection("Scripts2", required: false)
    @RenderSection("Scripts", required: false)

</body>
</html>

WebsiteQuyetTien_byAurora Team/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Quyết Tiến - Trang chủ</title>
    <link rel="shortcut icon" href="~/www.root/controller/loginController/images/favicon.png" />
    <meta name="description"
          content="Trang bán hàng của Cửa hàng Quyết Tiến - chuyên phân phối các thiết bị điện máy chất lượng, uy tín.">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Tập tin CSS Bootstrap-->
    <link href="~/www.root/shared/user_layout/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Tập tin CSS Font Awesome -->
    <link rel="stylesheet" href="~/www.root/shared/user_layout/vendor/font-awesome/css/font-awesome.min.css">
    <!-- Google fonts - Roboto -->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,500,700,300,100">
    <!-- owl carousel-->
    <link rel="stylesheet" href="~/www.root/shared/user_layout/vendor/owl.carousel/assets/owl.carousel.css">
    <link rel="stylesheet" href="~/www.root/shared/user_layout/vendor/owl.carousel/assets/owl.theme.default.css">
    <!-- Tập tin CSS chủ đề màu sắc Website-->
    <link rel="stylesheet" href="~/www.root/shared/user_layout/css/style.red.css" id="theme-stylesheet">
    <!-- Tập tin tự điều chỉnh CSS -->
    <link rel="stylesheet" href="~/www.root/shared/user_layout/css/custom.css">
    <!-- Logo nhận dạng Website -->
    <link rel="shortcut icon" href="favicon.png">
    <!-- Tweaks for older IEs-->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<body>
    @Html.Partial("~/Views/Shared/HeaderUserLayoutPartial.cshtml")
    <!-- *** NỘI DUNG *** -->
    @RenderBody()
    <!-- *** HẾT NỘI DUNG *** -->
    @Html.Partial("~/Views/Shared/FooterUserLayoutPatial.cshtml")
    <!-- *** CÁC TẬP TIN JAVASCRIPTS CẦN THIẾT *** -->
    <script src="~/www.root/shared/user_layout/vendor/jquery/jquery.min.js"></script>
    <!-- jQuery CDN -->
    <!--Easy autocomplete-->
    <link href="~/www.root/shared/easyAutocomplete/easy-autocomplete.css" rel="stylesheet" />
    <link href="~/www.root/shared/easyAutocomplete/easy-autocomplete.min.css" rel="stylesheet" />
    <link href="~/www.root/shared/easyAutocomplete/easy-autocomplete.themes.css" rel="stylesheet" />
    <link href="~/www.root/shared/easyAutocomplete/easy-autocomplete.themes.min.css" rel="stylesheet" />
    <script src="~/www.root/shared/easyAutocomplete/jquery.easy-autocomplete.js"></script>
    <script src="~/www.root/shared/easyAutocomplete/jquery.easy-autocomplete.min.js"></script>

    <script src="~/www.root/shared/user_layout/vendor/popper.js/umd/popper.min.js"></script>
    <script src="~/www.root/shared/user_layout/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/www.root/shared/user_layout/vendor/jquery.cookie/jquery.cookie.js"></script>
    <script src="~/www.root/shared/user_layout/vendor/owl.carousel/owl.carousel.min.js"></script>
    <script src="~/www.root/shared/user_layout/vendor/owl.carousel2.thumbs/owl.carousel2.thumbs.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js"></script>
    <script src="~/www.root/shared/user_layout/js/front.js"></script>
    <script src="~/www.root/controller/homeController/homeQT.js"></script>
    <!--- *** HẾT CÁC TẬP TIN JAVASCRIPTS CẦN THIẾT *** -->
</body>
</html>